### ISSUE TITLE
TargetCloseError: Protocol error (Page.printToPDF): Target closed

### ISSUE THREAD

**Issue by c-delouvencourt** [stefanzweifel/sidecar-browsershot#134]
## Bug description
I am trying to generate a pdf from a big html file with lots of images

## Steps to reproduce the problem:
`return BrowsershotLambda::url("https://api.meilleursbiens.com/api/v1/estimation/rapport-estimation/preview/dvlQ4WrStXDoL01Vd9NFjjqF9utO9QinackGlGkc2M3r/8474/1")
            ->setOption('protocolTimeout', 600_000)
            ->timeout(60 * 5)
            ->addChromiumArguments([
                "font-render-hinting" => "none",
                "force-color-profile" => "srgb",
            ])
            ->format('A4')
            ->margins(10, 0, 0, 0)
            ->showBackground()
            ->delay(10000)
            ->pdf();`

## Relevant log output
`Lambda Execution Exception for Wnx\\SidecarBrowsershot\\Functions\\BrowsershotFunction: Command failed: node ./browser.cjs -f file:///tmp/browsershot.js

TargetCloseError: Protocol error (Page.printToPDF): Target closed
    at CallbackRegistry.clear (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:75:36)
    at CdpCDPSession._onClosed (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:101:25)
    at #onClose (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:157:21)
    at WebSocket.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:47:30)
    at callListener (/opt/nodejs/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/opt/nodejs/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emitClose (/opt/nodejs/node_modules/ws/lib/websocket.js:265:10)
    at Socket.socketOnClose (/opt/nodejs/node_modules/ws/lib/websocket.js:1289:15)
    at Socket.emit (node:events:519:28) {
        cause: ProtocolError
        at <instance_members_initializer> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:96:14)
        at new Callback (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:100:16)
        at CallbackRegistry.create (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
        at Connection._rawSend (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:26)
        at CdpCDPSession.send (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:66:33)
        at CdpPage.createPDFStream (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:821:63)
        at CdpPage.pdf (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Page.js:849:37)
        at getOutput (/var/task/browser.cjs:50:54)
        at callChrome (/var/task/browser.cjs:392:27)
}`

**Comment by stefanzweifel** [comment]
Thanks for reporting, @c-delouvencourt 

As we can see from the stacktrace, this seems to be related to an AWS-SDK Dependency called [smithy](https://github.com/smithy-lang/smithy-typescript/tree/main/packages/core).
The AWS-SDK is provided by AWS itself and injected into the Lambda function at runtime (or compile time, I'm not sure)

Not sure how we could debug or resolve this issue. For simplicity, I've downloaded the produced HTML from your API and attached it to the issue.

Just for clarification: This is something that worked before and just now started to fail?
Or are you currently testing sidecar-browsershot and run into this issue?

---

Generating large PDFs seems to be a general issue with Puppeteer and Chromium. We had previous issues/discussions around this topic and never really found a good solution.
